### ISSUE TITLE
Colors in scripts

### ISSUE THREAD

**Issue by Dreadeath** [bram85/topydo#111]
Hi, there is no color support when topydo is run with e.g. `watch` command, even if `watch` is run with `--color` parameter. The same goes to something like `topydo > /tmp/todo`, the output is just plain text. I know it is mostly desirable behavior, so maybe `--forcecolor` parameter will be a nice feature.

**Comment by bram85** [comment]
Agreed. I and @mruwek have been thinking about a more flexible color output configuration. My proposal is as follows.

Currently we have the `color` option in the configuration file (boolean):

```ini
[topydo]
color = 0
```

My suggestion is that this option will take the following values instead:

* `0`: force no colors
* `1`: force colors, max. 16 colors
* `16`: force colors, max. 16 colors
* `256`: force colors, 256 colors
* empty or `auto`: current behavior, check whether topydo is connected to a TTY and disable colors if not. Otherwise print 16 colors (to be safe).

Besides this configuration option, a global commandline parameter should be added (`--color` or `-C`).

**Comment by Dreadeath** [comment]
@bram85, I have nothing to add, that would be great :)

**Comment by bram85** [comment]
Implemented in the `column-ui` branch, to be merged with `master`.
