### ISSUE TITLE
force completed tasks to use completed tag ? (for recurring tasks)

### ISSUE THREAD

**Issue by p-phillips** [bram85/topydo#178]
I have a lot of recurring tasks.  I don't like having the completed date stuck at the front - I'd rather have a completed tag (completed:2017-04-09 for example) at the end of the line with the rest of the administrivia.

Is this possible with the current system (couldn't see how to set a completed tag on the wiki) or would it be an enhancement request ?

Pete

**Comment by MinchinWeb** [comment]
Having the completed date at the start of the line is part of the [todo.txt format](https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format) that topydo uses.

However, very few tags are actually defined by the format itself, so noting keeps you from using a 'completed' tag to your own ends. Use the `tag` subcommand to do this. I.e.
```
topydo tag <item number> completed 2017-04-09
```
You can also run the same command again to change the completed date.

**Comment by p-phillips** [comment]
Hi WIlliam.

I think that's too much hassle!  :-)

I was thinking of a method to replace the  date at the start of the line
with a completed: tag automatically when I mark the task as done
(especially for recurring tasks), rather than having to do it manually.....
especially as I use column mode mainly so mark tasks as done with an 'x' in
that interface.

Thanks for replying.

Pete

**Comment by bram85** [comment]
It's not possible to replace the completion date at the start with a tagged completion date at the end of the line. Your request, as @MinchinWeb already mentioned, deviates from the todo.txt format. Therefore I cannot go along with this feature request. The main reason is that it will break compatibility with other todo.txt applications, which I deem unacceptable. Moreover, I'm afraid that one deviation from the format will lead to other deviations (even if they are optional), making the code more complex.

Since topydo is a commandline application using a plain text format, you could write a Bash function that does what you request:

```sh
function tdo {
  topydo tag -r $1 completed today # the -r is to convert 'today' to an absolute date
  topydo do $1
}
```

The disadvantage is that this is not possible from the prompt/column mode.

**Comment by p-phillips** [comment]
Hi Bram

Yes - I appreciate it would break the format, and that's not a good thing.

Great idea about the bash function - that would certainly help a lot.

Cheers both for your thoughts.
Pete
