### ISSUE TITLE
[EXPIRED] Windows standalone binary

### ISSUE THREAD

**Issue by sergeevabc** [bram85/topydo#187]
Dear Bram,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows w/o Python?
I’m told that [py2exe][1] or [nuitka][2] might help you to achieve that.

[1]: http://py2exe.org/
[2]: http://nuitka.net/

**Comment by bram85** [comment]
Any assistance on this would be welcome. py2exe does not support Python 3 (and seems abandoned), and I didn't get nuitka to work right away.

**Comment by sergeevabc** [comment]
Py2exe [supports][1] Python 3 since 2014, perhaps not all of 3.* minor modifications (tutorials: [one][2], [two][3]).
Also there are a few related answers on Stackoverflow advocating to try [CXFreeze][4] ([3.2][5] and [3.6][6]).

[1]: https://pypi.python.org/pypi/py2exe
[2]: http://www.py2exe.org/index.cgi/Tutorial
[3]: https://simpletutorials.com/c/2075/How+to+Create+an+Executable+from+Python+3+Code+using+py2exe
[4]: https://pypi.python.org/pypi/cx_Freeze
[5]: http://blog.notfaqs.com/2011/09/python-32-create-executable-with.html
[6]: https://regilanj.wordpress.com/2017/06/07/py-to-exe-in-python-3-6-1/

**Comment by RonCam** [comment]
@sergeevabc: Have you noticed, [there is a new release of _nuitka_](http://nuitka.net/posts/nuitka-release-0528.html), as of about a month ago?   

I'm happily using _topydo_ on two different distros of GNU/Linux, so this isn't applicable to me, personally, but it may be of interest to others.  I have no idea if it is easier to install and use than was the previous version.  

I went to the _nuitka_ site purely out of curiosity, since I noticed this _Issue_ was posted well before this latest _nuitka_ update became available and the OP hasn't posted again, since then.

**Comment by sergeevabc** [comment]
@bram85, would you mind giving Nuitka another chance to turn ```topydo``` into executable?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by bram85** [comment]
I don't have time for this at the moment. My initial comment still stands: "Any assistance on this would be welcome."
