### ISSUE TITLE
Printing terminal output to printer, is this possible from prompt mode?

### ISSUE THREAD

**Issue by RonCam** [bram85/topydo#197]
I would like a fast way of getting selected reminders to a slip of paper, without hand-copying from the screen.

For example, this works:
`> topydo ls | lpr`

but this fails to activate the printer:
`topydo> ls | lpr`

If I have my output formatted in a special way, while in prompt mode, wouldn't it be easier to reproduce this on the printer while in this mode, without exiting to bash?

I thought this might do it, while in the prompt mode, but it still doesn't start the printer:
```
[aliases]
lpt = ls | lpt
```
Or does one copy the format string in prompt mode, exit to bash, and then paste it back again?  Or, am I missing a better and easier way?  For example, is it possible for me to write a script to automate it?

**Comment by bram85** [comment]
Piping data is a shell feature, which is not supported by topydo prompt. The prompt is meant for topydo subcommands, not system commands. I don't intend to add this, that's why we have the original commandline interface in the first place. That allows you to combine topydo with the rich syntax and concepts that come with a real shell.

With the info on [this page](https://topydo.org/#ExternalCommands), you could build a workaround: create a small shell script that invokes topydo the way you want and pipe to lpr. Then create a toppio alias for `edit -E`, called `print` and then the `print` command will be recognized in prompt mode.
